
title: NerdWyrm Nature Journal
description: A digital notebook of outdoor observations and adventures.
url: https://nerdwyrm.com
baseurl: ""

# Switch to Midnight theme (GitHub Pages supported)
theme: jekyll-theme-midnight

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks for posts
permalink: /:categories/:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
